# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\SplashScreenForm.py'],
    pathex=['D:\\Qt_designer\\AutoServiseProject'],
    binaries=[],
    datas=[
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\AutoService.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\Car.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\CarOrder.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\Employee.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\Order.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\Service.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\ServiceManager.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\signals.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\Clases\\TempFile.py', 'Clases'),
        ('D:\\Qt_designer\\AutoServiseProject\\DataBase\\DataBase.py', 'DataBase'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\AnalyticsForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\CarManagerForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\ChangingStatusForClientsForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\ClientManagementForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\DetailedOrderForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\DisplayHistoryCarsForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\EditingForCarsForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\EditingForEmployeeForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\EditingForServiceForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\EmployeeManagementForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\EmployeeReportForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\LoginForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\MainForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\OrderMakingForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\RegisterForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\ServiceManagementForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\SplashScreenForm.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\MainFunctionality\\test.py', 'MainFunctionality'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\AnalyticsForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\CarManagementForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\ChangingStatusForClientsForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\ClientManagementForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\DetailedServiceForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\DisplayHistoryCarsForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\EditingForCarsForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\EditingForEmpoleeForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\EditingForServicesForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\EmployeeManagementForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\EmployeeReportForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\LoginForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\MainForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\NewMainFormNotUsedYet_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\OrderMakingForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\RegisterForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\res.qrc', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\ServiceManagementForm_design.py', 'FormDesign\\FormHandlers'),
        ('D:\\Qt_designer\\AutoServiseProject\\FormDesign\\FormHandlers\\SplashScreenForm_design.py', 'FormDesign\\FormHandlers')
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AutoService',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AutoService'
)
