# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientManegementForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1122, 640)
        self.label_mainClients = QtWidgets.QLabel(Form)
        self.label_mainClients.setGeometry(QtCore.QRect(260, 10, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_mainClients.setFont(font)
        self.label_mainClients.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mainClients.setObjectName("label_mainClients")
        self.labeClientsOutputChoose = QtWidgets.QLabel(Form)
        self.labeClientsOutputChoose.setGeometry(QtCore.QRect(40, 140, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labeClientsOutputChoose.setFont(font)
        self.labeClientsOutputChoose.setObjectName("labeClientsOutputChoose")
        self.tableWidgetForOutputClients = QtWidgets.QTableWidget(Form)
        self.tableWidgetForOutputClients.setGeometry(QtCore.QRect(40, 190, 931, 441))
        self.tableWidgetForOutputClients.setObjectName("tableWidgetForOutputClients")
        self.tableWidgetForOutputClients.setColumnCount(7)
        self.tableWidgetForOutputClients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForOutputClients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForOutputClients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForOutputClients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForOutputClients.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForOutputClients.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForOutputClients.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForOutputClients.setHorizontalHeaderItem(6, item)
        self.comboBoxForChosingTypyOfPrintClients = QtWidgets.QComboBox(Form)
        self.comboBoxForChosingTypyOfPrintClients.setGeometry(QtCore.QRect(160, 140, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxForChosingTypyOfPrintClients.setFont(font)
        self.comboBoxForChosingTypyOfPrintClients.setObjectName("comboBoxForChosingTypyOfPrintClients")
        self.comboBoxForChosingTypyOfPrintClients.addItem("")
        self.comboBoxForChosingTypyOfPrintClients.addItem("")
        self.comboBoxForChosingTypyOfPrintClients.addItem("")
        self.pushButton_ForAplyPrintingClients = QtWidgets.QPushButton(Form)
        self.pushButton_ForAplyPrintingClients.setGeometry(QtCore.QRect(400, 130, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ForAplyPrintingClients.setFont(font)
        self.pushButton_ForAplyPrintingClients.setStyleSheet("QPushButton {\n"
                                                             "    background-color: #006400; /* Dark green color */\n"
                                                             "    color: white; /* Text color */\n"
                                                             "    border-radius: 5px; /* Rounded corners, adjust as needed */\n"
                                                             "    padding: 5px; /* Padding inside the button */\n"
                                                             "    border: none; /* No border */\n"
                                                             "}\n"
                                                             "\n"
                                                             "QPushButton:hover {\n"
                                                             "    background-color: #65B969; /* Light green color */\n"
                                                             "}\n"
                                                             "")
        self.pushButton_ForAplyPrintingClients.setObjectName("pushButton_ForAplyPrintingClients")
        self.comboBoxForChosingClients = QtWidgets.QComboBox(Form)
        self.comboBoxForChosingClients.setGeometry(QtCore.QRect(590, 80, 481, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxForChosingClients.setFont(font)
        self.comboBoxForChosingClients.setObjectName("comboBoxForChosingClients")
        self.comboBoxForChosingClients.addItem("")
        self.pushButtonForAplyClients = QtWidgets.QPushButton(Form)
        self.pushButtonForAplyClients.setGeometry(QtCore.QRect(670, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonForAplyClients.setFont(font)
        self.pushButtonForAplyClients.setObjectName("pushButtonForAplyClients")
        self.pushButtonForDenyClients = QtWidgets.QPushButton(Form)
        self.pushButtonForDenyClients.setGeometry(QtCore.QRect(850, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonForDenyClients.setFont(font)
        self.pushButtonForDenyClients.setObjectName("pushButtonForDenyClients")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_mainClients.setText(_translate("Form", "Потенційні клієнти"))
        self.labeClientsOutputChoose.setText(_translate("Form", "Клієнти:"))
        item = self.tableWidgetForOutputClients.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ім\'я"))
        item = self.tableWidgetForOutputClients.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Прізвище"))
        item = self.tableWidgetForOutputClients.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Телефон"))
        item = self.tableWidgetForOutputClients.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Марка"))
        item = self.tableWidgetForOutputClients.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Модель"))
        item = self.tableWidgetForOutputClients.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Рік випуску"))
        item = self.tableWidgetForOutputClients.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Дата відвідування"))
        self.comboBoxForChosingTypyOfPrintClients.setItemText(0, _translate("Form", "Усі"))
        self.comboBoxForChosingTypyOfPrintClients.setItemText(1, _translate("Form", "Майбутні"))
        self.comboBoxForChosingTypyOfPrintClients.setItemText(2, _translate("Form", "Минулі"))
        self.pushButton_ForAplyPrintingClients.setText(_translate("Form", "Вивести"))
        self.comboBoxForChosingClients.setItemText(0, _translate("Form", "Оберіть клієнта"))
        self.pushButtonForAplyClients.setText(_translate("Form", "Виконано"))
        self.pushButtonForDenyClients.setText(_translate("Form", "Видалити"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
