# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DisplayHistoryCarsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 571)
        self.label_main_auto = QtWidgets.QLabel(Form)
        self.label_main_auto.setGeometry(QtCore.QRect(210, 0, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_main_auto.setFont(font)
        self.label_main_auto.setObjectName("label_main_auto")
        self.labelCarChoise = QtWidgets.QLabel(Form)
        self.labelCarChoise.setGeometry(QtCore.QRect(60, 80, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCarChoise.setFont(font)
        self.labelCarChoise.setObjectName("labelCarChoise")
        self.comboBoxForSorting = QtWidgets.QComboBox(Form)
        self.comboBoxForSorting.setGeometry(QtCore.QRect(200, 80, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxForSorting.setFont(font)
        self.comboBoxForSorting.setObjectName("comboBoxForSorting")
        self.pushButtonAplySort = QtWidgets.QPushButton(Form)
        self.pushButtonAplySort.setGeometry(QtCore.QRect(500, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAplySort.setFont(font)
        self.pushButtonAplySort.setObjectName("pushButtonAplySort")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 130, 601, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DisplayHistoryCarsForm"))
        self.label_main_auto.setText(_translate("Form", "Виведення історіїї замовлення"))
        self.labelCarChoise.setText(_translate("Form", "Виберіть авто:"))
        self.pushButtonAplySort.setText(_translate("Form", "Вивести"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Авто"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Послуги"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Ціна"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Дата"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
