# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1178, 344)
        self.label_main = QtWidgets.QLabel(Form)
        self.label_main.setGeometry(QtCore.QRect(260, 30, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_main.setFont(font)
        self.label_main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main.setObjectName("label_main")
        self.pushButtonForWorkWithAuto = QtWidgets.QPushButton(Form)
        self.pushButtonForWorkWithAuto.setGeometry(QtCore.QRect(50, 120, 241, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonForWorkWithAuto.setFont(font)
        self.pushButtonForWorkWithAuto.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonForWorkWithAuto.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButtonForWorkWithAuto.setObjectName("pushButtonForWorkWithAuto")
        self.pushButtonForWorkWithWorkers = QtWidgets.QPushButton(Form)
        self.pushButtonForWorkWithWorkers.setGeometry(QtCore.QRect(300, 120, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonForWorkWithWorkers.setFont(font)
        self.pushButtonForWorkWithWorkers.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonForWorkWithWorkers.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButtonForWorkWithWorkers.setObjectName("pushButtonForWorkWithWorkers")
        self.pushButtonForOrderCreating = QtWidgets.QPushButton(Form)
        self.pushButtonForOrderCreating.setGeometry(QtCore.QRect(540, 120, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonForOrderCreating.setFont(font)
        self.pushButtonForOrderCreating.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonForOrderCreating.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButtonForOrderCreating.setObjectName("pushButtonForOrderCreating")
        self.pushButtonForOrderHistory = QtWidgets.QPushButton(Form)
        self.pushButtonForOrderHistory.setGeometry(QtCore.QRect(780, 120, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonForOrderHistory.setFont(font)
        self.pushButtonForOrderHistory.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonForOrderHistory.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButtonForOrderHistory.setObjectName("pushButtonForOrderHistory")
        self.pushButtonServiseAdd = QtWidgets.QPushButton(Form)
        self.pushButtonServiseAdd.setGeometry(QtCore.QRect(160, 270, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonServiseAdd.setFont(font)
        self.pushButtonServiseAdd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonServiseAdd.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButtonServiseAdd.setObjectName("pushButtonServiseAdd")
        self.logoutButton = QtWidgets.QPushButton(Form)
        self.logoutButton.setGeometry(QtCore.QRect(1080, 40, 80, 80))
        self.logoutButton.setText("")
        self.logoutButton.setObjectName("logoutButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1020, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_EmpoyeeReporting = QtWidgets.QPushButton(Form)
        self.pushButton_EmpoyeeReporting.setGeometry(QtCore.QRect(680, 270, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_EmpoyeeReporting.setFont(font)
        self.pushButton_EmpoyeeReporting.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_EmpoyeeReporting.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButton_EmpoyeeReporting.setObjectName("pushButton_EmpoyeeReporting")
        self.pushButtonServiceAnalytics = QtWidgets.QPushButton(Form)
        self.pushButtonServiceAnalytics.setGeometry(QtCore.QRect(420, 270, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonServiceAnalytics.setFont(font)
        self.pushButtonServiceAnalytics.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonServiceAnalytics.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButtonServiceAnalytics.setObjectName("pushButtonServiceAnalytics")
        self.pushButton_PotentialClients = QtWidgets.QPushButton(Form)
        self.pushButton_PotentialClients.setGeometry(QtCore.QRect(420, 190, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_PotentialClients.setFont(font)
        self.pushButton_PotentialClients.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_PotentialClients.setStyleSheet("background-color: rgb(163, 193, 218);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.pushButton_PotentialClients.setObjectName("pushButton_PotentialClients")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_main.setText(_translate("Form", "Головне меню програми"))
        self.pushButtonForWorkWithAuto.setText(_translate("Form", "Робота з автомобілями"))
        self.pushButtonForWorkWithWorkers.setText(_translate("Form", "Робота з працівниками"))
        self.pushButtonForOrderCreating.setText(_translate("Form", "Створення замовлення"))
        self.pushButtonForOrderHistory.setText(_translate("Form", "Виведення історії авто"))
        self.pushButtonServiseAdd.setText(_translate("Form", "Робота з послугами"))
        self.label.setText(_translate("Form", "Вихід з акаута:"))
        self.pushButton_EmpoyeeReporting.setText(_translate("Form", "Звітність парцівників"))
        self.pushButtonServiceAnalytics.setText(_translate("Form", "Аналітика автосервісу"))
        self.pushButton_PotentialClients.setText(_translate("Form", "Клієнти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
