# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalyticsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 965)
        self.comboBoxForSelectGraphs = QtWidgets.QComboBox(Form)
        self.comboBoxForSelectGraphs.setGeometry(QtCore.QRect(50, 100, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxForSelectGraphs.setFont(font)
        self.comboBoxForSelectGraphs.setObjectName("comboBoxForSelectGraphs")
        self.pushButtonForOutputGraphs = QtWidgets.QPushButton(Form)
        self.pushButtonForOutputGraphs.setGeometry(QtCore.QRect(650, 90, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonForOutputGraphs.setFont(font)
        self.pushButtonForOutputGraphs.setStyleSheet("QPushButton {\n"
"    background-color: #006400; /* Dark green color */\n"
"    color: white; /* Text color */\n"
"    border-radius: 5px; /* Rounded corners, adjust as needed */\n"
"    padding: 5px; /* Padding inside the button */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #65B969; /* Light green color */\n"
"}\n"
"")
        self.pushButtonForOutputGraphs.setObjectName("pushButtonForOutputGraphs")
        self.label_main_Alnalytics = QtWidgets.QLabel(Form)
        self.label_main_Alnalytics.setGeometry(QtCore.QRect(360, 20, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_main_Alnalytics.setFont(font)
        self.label_main_Alnalytics.setObjectName("label_main_Alnalytics")
        self.widget_ForOutpurGraphs = QtWidgets.QWidget(Form)
        self.widget_ForOutpurGraphs.setGeometry(QtCore.QRect(50, 150, 1000, 800))
        self.widget_ForOutpurGraphs.setObjectName("widget_ForOutpurGraphs")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AnalyticsForm"))
        self.pushButtonForOutputGraphs.setText(_translate("Form", "Вивести графік"))
        self.label_main_Alnalytics.setText(_translate("Form", "Аналітика автосервісу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
