# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditingForServicesForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.labelServiceIput = QtWidgets.QLabel(Form)
        self.labelServiceIput.setGeometry(QtCore.QRect(10, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelServiceIput.setFont(font)
        self.labelServiceIput.setObjectName("labelServiceIput")
        self.lineEditForPriceEditingInput = QtWidgets.QLineEdit(Form)
        self.lineEditForPriceEditingInput.setGeometry(QtCore.QRect(120, 140, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForPriceEditingInput.setFont(font)
        self.lineEditForPriceEditingInput.setObjectName("lineEditForPriceEditingInput")
        self.pushButtonForDenyEditingService = QtWidgets.QPushButton(Form)
        self.pushButtonForDenyEditingService.setGeometry(QtCore.QRect(200, 210, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonForDenyEditingService.setFont(font)
        self.pushButtonForDenyEditingService.setStyleSheet("QPushButton {\n"
"    background-color: #8B0000; /* Темно-червоний колір */\n"
"    color: white; /* Колір тексту */\n"
"    border-radius: 5px; /* Закруглені кути, можна налаштувати за потреби */\n"
"    padding: 5px; /* Відступ всередині кнопки */\n"
"    border: none; /* Без рамки */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF6347; /* Світло-червоний колір */\n"
"}\n"
"")
        self.pushButtonForDenyEditingService.setObjectName("pushButtonForDenyEditingService")
        self.lineEditForServiceEditingInput = QtWidgets.QLineEdit(Form)
        self.lineEditForServiceEditingInput.setGeometry(QtCore.QRect(114, 94, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForServiceEditingInput.setFont(font)
        self.lineEditForServiceEditingInput.setObjectName("lineEditForServiceEditingInput")
        self.pushButton_ForAplyEditingService = QtWidgets.QPushButton(Form)
        self.pushButton_ForAplyEditingService.setGeometry(QtCore.QRect(20, 210, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ForAplyEditingService.setFont(font)
        self.pushButton_ForAplyEditingService.setStyleSheet("QPushButton {\n"
"    background-color: #006400; /* Dark green color */\n"
"    color: white; /* Text color */\n"
"    border-radius: 5px; /* Rounded corners, adjust as needed */\n"
"    padding: 5px; /* Padding inside the button */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #65B969; /* Light green color */\n"
"}\n"
"")
        self.pushButton_ForAplyEditingService.setObjectName("pushButton_ForAplyEditingService")
        self.labeForPricelIput = QtWidgets.QLabel(Form)
        self.labeForPricelIput.setGeometry(QtCore.QRect(50, 140, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labeForPricelIput.setFont(font)
        self.labeForPricelIput.setObjectName("labeForPricelIput")
        self.label_For_Editing_Services = QtWidgets.QLabel(Form)
        self.label_For_Editing_Services.setGeometry(QtCore.QRect(30, 20, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_For_Editing_Services.setFont(font)
        self.label_For_Editing_Services.setObjectName("label_For_Editing_Services")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Editing"))
        self.labelServiceIput.setText(_translate("Form", "Послуга:"))
        self.pushButtonForDenyEditingService.setText(_translate("Form", "Скасувати"))
        self.pushButton_ForAplyEditingService.setText(_translate("Form", "Підтвердити"))
        self.labeForPricelIput.setText(_translate("Form", "Ціна:"))
        self.label_For_Editing_Services.setText(_translate("Form", "Редагування Послуг"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
