# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditingForCarsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(457, 281)
        self.label_For_Editing_auto = QtWidgets.QLabel(Form)
        self.label_For_Editing_auto.setGeometry(QtCore.QRect(80, 10, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_For_Editing_auto.setFont(font)
        self.label_For_Editing_auto.setObjectName("label_For_Editing_auto")
        self.labelMarkIput = QtWidgets.QLabel(Form)
        self.labelMarkIput.setGeometry(QtCore.QRect(100, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelMarkIput.setFont(font)
        self.labelMarkIput.setObjectName("labelMarkIput")
        self.lineEditForYearCreatInput = QtWidgets.QLineEdit(Form)
        self.lineEditForYearCreatInput.setGeometry(QtCore.QRect(190, 170, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForYearCreatInput.setFont(font)
        self.lineEditForYearCreatInput.setObjectName("lineEditForYearCreatInput")
        self.lineEditForMarkInput = QtWidgets.QLineEdit(Form)
        self.lineEditForMarkInput.setGeometry(QtCore.QRect(184, 84, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForMarkInput.setFont(font)
        self.lineEditForMarkInput.setObjectName("lineEditForMarkInput")
        self.lineEditForModelInput = QtWidgets.QLineEdit(Form)
        self.lineEditForModelInput.setGeometry(QtCore.QRect(190, 130, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForModelInput.setFont(font)
        self.lineEditForModelInput.setObjectName("lineEditForModelInput")
        self.labeForModelIput = QtWidgets.QLabel(Form)
        self.labeForModelIput.setGeometry(QtCore.QRect(90, 129, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labeForModelIput.setFont(font)
        self.labeForModelIput.setObjectName("labeForModelIput")
        self.labelYearInput = QtWidgets.QLabel(Form)
        self.labelYearInput.setGeometry(QtCore.QRect(50, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelYearInput.setFont(font)
        self.labelYearInput.setObjectName("labelYearInput")
        self.pushButtonForDenyEditingAuto = QtWidgets.QPushButton(Form)
        self.pushButtonForDenyEditingAuto.setGeometry(QtCore.QRect(240, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonForDenyEditingAuto.setFont(font)
        self.pushButtonForDenyEditingAuto.setStyleSheet("QPushButton {\n"
"    background-color: #8B0000; /* Темно-червоний колір */\n"
"    color: white; /* Колір тексту */\n"
"    border-radius: 5px; /* Закруглені кути, можна налаштувати за потреби */\n"
"    padding: 5px; /* Відступ всередині кнопки */\n"
"    border: none; /* Без рамки */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF6347; /* Світло-червоний колір */\n"
"}\n"
"")
        self.pushButtonForDenyEditingAuto.setObjectName("pushButtonForDenyEditingAuto")
        self.pushButton_ForAplyEditingAuto = QtWidgets.QPushButton(Form)
        self.pushButton_ForAplyEditingAuto.setGeometry(QtCore.QRect(60, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ForAplyEditingAuto.setFont(font)
        self.pushButton_ForAplyEditingAuto.setStyleSheet("QPushButton {\n"
"    background-color: #006400; /* Dark green color */\n"
"    color: white; /* Text color */\n"
"    border-radius: 5px; /* Rounded corners, adjust as needed */\n"
"    padding: 5px; /* Padding inside the button */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #65B969; /* Light green color */\n"
"}\n"
"")
        self.pushButton_ForAplyEditingAuto.setObjectName("pushButton_ForAplyEditingAuto")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Editing"))
        self.label_For_Editing_auto.setText(_translate("Form", "Редагування Авто"))
        self.labelMarkIput.setText(_translate("Form", "Марка:"))
        self.labeForModelIput.setText(_translate("Form", "Модель:"))
        self.labelYearInput.setText(_translate("Form", "Рік випуску:"))
        self.pushButtonForDenyEditingAuto.setText(_translate("Form", "Скасувати"))
        self.pushButton_ForAplyEditingAuto.setText(_translate("Form", "Підтвердити"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
