# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditingForEmpoleeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 300)
        self.lineEditForIncomeInput = QtWidgets.QLineEdit(Form)
        self.lineEditForIncomeInput.setGeometry(QtCore.QRect(210, 180, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForIncomeInput.setFont(font)
        self.lineEditForIncomeInput.setObjectName("lineEditForIncomeInput")
        self.labelNameInput = QtWidgets.QLabel(Form)
        self.labelNameInput.setGeometry(QtCore.QRect(140, 90, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelNameInput.setFont(font)
        self.labelNameInput.setObjectName("labelNameInput")
        self.labelIncomeIInput = QtWidgets.QLabel(Form)
        self.labelIncomeIInput.setGeometry(QtCore.QRect(120, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelIncomeIInput.setFont(font)
        self.labelIncomeIInput.setObjectName("labelIncomeIInput")
        self.lineEditForPositionInput = QtWidgets.QLineEdit(Form)
        self.lineEditForPositionInput.setGeometry(QtCore.QRect(210, 140, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForPositionInput.setFont(font)
        self.lineEditForPositionInput.setObjectName("lineEditForPositionInput")
        self.pushButtonForDenyEditingEmpoyee = QtWidgets.QPushButton(Form)
        self.pushButtonForDenyEditingEmpoyee.setGeometry(QtCore.QRect(260, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonForDenyEditingEmpoyee.setFont(font)
        self.pushButtonForDenyEditingEmpoyee.setStyleSheet("QPushButton {\n"
"    background-color: #8B0000; /* Темно-червоний колір */\n"
"    color: white; /* Колір тексту */\n"
"    border-radius: 5px; /* Закруглені кути, можна налаштувати за потреби */\n"
"    padding: 5px; /* Відступ всередині кнопки */\n"
"    border: none; /* Без рамки */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF6347; /* Світло-червоний колір */\n"
"}\n"
"")
        self.pushButtonForDenyEditingEmpoyee.setObjectName("pushButtonForDenyEditingEmpoyee")
        self.lineEditForNameInput = QtWidgets.QLineEdit(Form)
        self.lineEditForNameInput.setGeometry(QtCore.QRect(204, 94, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditForNameInput.setFont(font)
        self.lineEditForNameInput.setObjectName("lineEditForNameInput")
        self.pushButton_ForAplyEditingEmployee = QtWidgets.QPushButton(Form)
        self.pushButton_ForAplyEditingEmployee.setGeometry(QtCore.QRect(80, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ForAplyEditingEmployee.setFont(font)
        self.pushButton_ForAplyEditingEmployee.setStyleSheet("QPushButton {\n"
"    background-color: #006400; /* Dark green color */\n"
"    color: white; /* Text color */\n"
"    border-radius: 5px; /* Rounded corners, adjust as needed */\n"
"    padding: 5px; /* Padding inside the button */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #65B969; /* Light green color */\n"
"}\n"
"")
        self.pushButton_ForAplyEditingEmployee.setObjectName("pushButton_ForAplyEditingEmployee")
        self.labeForPositionInput = QtWidgets.QLabel(Form)
        self.labeForPositionInput.setGeometry(QtCore.QRect(100, 139, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labeForPositionInput.setFont(font)
        self.labeForPositionInput.setObjectName("labeForPositionInput")
        self.label_For_Editing_Employee = QtWidgets.QLabel(Form)
        self.label_For_Editing_Employee.setGeometry(QtCore.QRect(30, 20, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_For_Editing_Employee.setFont(font)
        self.label_For_Editing_Employee.setObjectName("label_For_Editing_Employee")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Editing"))
        self.labelNameInput.setText(_translate("Form", "Ім\'я:"))
        self.labelIncomeIInput.setText(_translate("Form", "Дохід:"))
        self.pushButtonForDenyEditingEmpoyee.setText(_translate("Form", "Скасувати"))
        self.pushButton_ForAplyEditingEmployee.setText(_translate("Form", "Підтвердити"))
        self.labeForPositionInput.setText(_translate("Form", "Птосада:"))
        self.label_For_Editing_Employee.setText(_translate("Form", "Редагування Працівників"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
